name: Practice Project
on: [push , workflow_dispatch]
jobs:
  Lint:
   runs-on: ubuntu-latest
   steps:
     - name : Download Code
       uses: actions/checkout@v3
     - name: Install Node Js 
       uses: actions/setup-node@v4
       with: 
        node-version: '23'
     - name: Install Dependencies
       run: npm ci
     - name: Executing Lint
       run: npm rum lint     