name: Practice Project
on: [push , workflow_dispatch]
jobs:
  Lint:
   runs-on: ubuntu-latest
   steps:
     - name : Download Code
       uses: actions/checkout@v3
     - name: Install Node Js 
       uses: actions/setup-node@v3
       with: 
        node-version: '23'
     - name: Install Dependencies
       run: npm ci
     - name: Executing Lint
       run: npm rum lint     
  Test:
   needs: Lint
   runs-on: ubuntu-latest
   steps:
    - name: Download Code 
      uses: actions/checkout@v3
    - name: Install Node Js 
      uses: actions/setup-node@v3
      with:
        node-version: '23'
    - name: Install Dependencies
      run: npm ci
    - name: Executing Test
      run: npm run test
    - name: Console Log
      run: echo "Test Completed!!"
  deploy:
   needs: [Lint,Test]
   runs-on: ubuntu-latest
   steps:
      - name: Download Code 
        uses: actions/checkout@v3
      - name: Install Node Js 
        uses: actions/setup-node@v3
        with:
         node-version: '23'
      - name: Install Dependencies
        run: npm ci
      - name: Executing Test
        run: npm run deploy
      - name: Console Log
        run: echo "Deply Completed!!"
                